export const INIT_APP = "INIT_APP";
export const INIT_APP_WITH_QUERY = "INIT_APP_WITH_QUERY";
export const SORT_MOVIES = "SORT_MOVIES";
export const FILTER_CHANGED = "FILTER_CHANGED";
export const SEARCH_CHANGED = "SEARCH_CHANGED";
